import uuid

from django.db import models

from store.models import Store


class ChatSession(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    store = models.ForeignKey(Store, on_delete=models.CASCADE, related_name="sessions")
    session_id = models.UUIDField(
        help_text="Generated by widget, passed in every request"
    )
    customer_email = models.EmailField(
        null=True, blank=True, help_text="Not collected in PoC"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("store", "session_id")

    def __str__(self) -> str:
        return f"Session {self.session_id} (Store: {self.store_id})"

    def get_last_n_messages(self, n: int = 5):
        """Returns the last N messages for this session, ordered chronologically."""
        return self.messages.order_by("-created_at")[:n][::-1]


class ChatMessage(models.Model):
    ROLE_CHOICES = [
        ("user", "User"),
        ("assistant", "Assistant"),
    ]

    ESCALATION_REASONS = [
        ("low_confidence", "Low Confidence"),
        ("keyword_trigger", "Keyword Trigger"),
        ("customer_request", "Customer Request"),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.ForeignKey(
        ChatSession, on_delete=models.CASCADE, related_name="messages"
    )
    role = models.CharField(max_length=10, choices=ROLE_CHOICES)
    content = models.TextField()
    confidence_score = models.FloatField(
        null=True, blank=True, help_text="Set only on assistant messages"
    )
    escalated = models.BooleanField(default=False)
    escalation_reason = models.CharField(
        max_length=20,
        choices=ESCALATION_REASONS,
        null=True,
        blank=True,
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self) -> str:
        preview = self.content[:40] if self.content else ""
        return f"[{self.role}] {preview}..."
