# Generated by Django 6.0.6 on 2026-08-08 15:20

import uuid

import django.db.models.deletion
from django.db import migrations, models


def create_store_subscriptions(apps, schema_editor):
    Store = apps.get_model("store", "Store")
    Subscription = apps.get_model("billing", "Subscription")
    status_map = {
        "trial": "trialing",
        "active": "active",
        "cancelled": "canceled",
        "expired": "revoked",
        "suspended": "revoked",
    }
    Subscription.objects.bulk_create(
        [
            Subscription(
                store=store,
                plan_key=store.plan
                or ("trial" if store.subscription_status == "trial" else "starter"),
                status=status_map.get(store.subscription_status, "revoked"),
                current_period_end=store.billing_cycle_end or store.trial_ends_at,
            )
            for store in Store.objects.all()
        ],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("store", "0004_resize_embeddings_to_1024"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolarWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                ("payload", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "polar_customer_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "polar_subscription_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "polar_product_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("plan_key", models.CharField(default="trial", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("trialing", "Trialing"),
                            ("active", "Active"),
                            ("past_due", "Past due"),
                            ("canceled", "Canceled"),
                            ("revoked", "Revoked"),
                            ("unpaid", "Unpaid"),
                        ],
                        default="trialing",
                        max_length=20,
                    ),
                ),
                ("cancel_at_period_end", models.BooleanField(default=False)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="store.store",
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_store_subscriptions, migrations.RunPython.noop),
    ]
