# Generated by Django 6.0.6 on 2026-06-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatmessage_metadata_chatmessage_response_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Collected from pre-chat form', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='customer_phone',
            field=models.CharField(blank=True, help_text='Collected from pre-chat form', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='customer_email',
            field=models.EmailField(blank=True, help_text='Collected from pre-chat form', max_length=254, null=True),
        ),
    ]
