# Generated by Django 5.2.15 on 2026-06-26 19:41

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "api_key_hash",
                    models.CharField(
                        help_text="SHA-256 of raw API key", max_length=64, unique=True
                    ),
                ),
                (
                    "wc_url",
                    models.URLField(
                        blank=True,
                        help_text="Merchant's WooCommerce store URL",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "wc_consumer_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "wc_consumer_secret",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "merchant_email",
                    models.EmailField(
                        blank=True,
                        help_text="Escalation destination, trial reminders",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        default="trial",
                        help_text="trial / active / cancelled / expired / suspended",
                        max_length=50,
                    ),
                ),
                (
                    "plan",
                    models.CharField(
                        blank=True,
                        help_text="starter / growth / pro / null",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("trial_ends_at", models.DateTimeField(blank=True, null=True)),
                ("billing_cycle_end", models.DateTimeField(blank=True, null=True)),
                (
                    "conversation_count",
                    models.IntegerField(
                        default=0,
                        help_text="Incremented per ChatSession, reset monthly",
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
