# Generated by Django 5.2.15 on 2026-06-26 19:45

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        VectorExtension(),
    ]
